=== yawlfoundation/yawl/trunk/newyawl/filmYAWL/trunk/forms/schemas/castInfoType.xsd
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.yawlfoundation.org/sb/castInfo"
	xmlns:tns="http://www.yawlfoundation.org/sb/castInfo" attributeFormDefault="unqualified"
	elementFormDefault="unqualified">

	<element name="Input_Cast_List" type="tns:Input_Cast_ListType" />

	<complexType name="Input_Cast_ListType">
		<sequence>
			<element name="production" type="string" />	<!--Input Only-->
			<element name="castInfo" type="tns:castInfoType" />	<!--Input/Output-->
		</sequence>
	</complexType>

	<complexType name="castInfoType">
		<sequence>
			<element name="singleCastInfo" minOccurs="0" maxOccurs="unbounded" type="tns:singleCastInfoType" />
		</sequence>
	</complexType>

	<complexType name="singleCastInfoType">
		<sequence>
			<element name="character" type="string" />
			<element name="artist" type="string" />
			<element name="agent" type="string" />
			<element name="agentContactNo" type="string" />
		</sequence>
	</complexType>
</schema>

=== yawlfoundation/yawl/trunk/newyawl/filmYAWL/trunk/forms/xml/castInfoType.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns2:Input_Cast_List xmlns:ns2="http://www.yawlfoundation.org/sb/castInfo" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.yawlfoundation.org/sb/castInfo ../castInfoType.xsd ">
  <production>production</production>
  <castInfo>
    <singleCastInfo>
      <character>character</character>
      <artist>artist</artist>
      <agent>agent</agent>
      <agentContactNo>agentContactNo</agentContactNo>
    </singleCastInfo>
  </castInfo>
</ns2:Input_Cast_List>
