=== yawlfoundation/yawl/trunk/newyawl/filmYAWL/trunk/forms/schemas/crewInfoType.xsd
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.yawlfoundation.org/sb/crewInfo"
	xmlns:tns="http://www.yawlfoundation.org/sb/crewInfo" attributeFormDefault="unqualified"
	elementFormDefault="unqualified">

	<element name="Input_Crew_List" type="tns:Input_Crew_ListType" />

	<complexType name="Input_Crew_ListType">
		<sequence>
			<element name="production" type="string" />	<!--Input Only-->
			<element name="crewInfo" type="tns:crewInfoType" />	<!--Input/Output-->
		</sequence>
	</complexType>

	<complexType name="crewInfoType">
		<sequence>
			<element name="singleCrewInfo" minOccurs="0" maxOccurs="unbounded" type="tns:singleCrewInfoType" />
		</sequence>
	</complexType>

	<complexType name="singleCrewInfoType">
		<sequence>
			<element name="role" type="string" />
			<element name="firstName" type="string" />
			<element name="lastName" type="string" />
			<element name="contactNo" type="string" />
			<element name="email" type="string" />
		</sequence>
	</complexType>
</schema>

=== yawlfoundation/yawl/trunk/newyawl/filmYAWL/trunk/forms/xml/crewInfoType.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns2:Input_Crew_List xmlns:ns2="http://www.yawlfoundation.org/sb/crewInfo" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.yawlfoundation.org/sb/crewInfo ../crewInfoType.xsd ">
  <production>production</production>
  <crewInfo>
    <singleCrewInfo>
      <role>role</role>
      <firstName>firstName</firstName>
      <lastName>lastName</lastName>
      <contactNo>contactNo</contactNo>
      <email>email</email>
    </singleCrewInfo>
  </crewInfo>
</ns2:Input_Crew_List>
