=== yawlfoundation/yawl/trunk/newyawl/filmYAWL/trunk/JSP/continuityReport/continuityInfoType.xsd
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.yawlfoundation.org/sb/continuityInfo"
	xmlns:tns="http://www.yawlfoundation.org/sb/continuityInfo"
	attributeFormDefault="unqualified" elementFormDefault="unqualified">
	
	<element name="Fill_Out_Continuity_Report" type="tns:Fill_Out_Continuity_ReportType"/>
	
	<complexType name="Fill_Out_Continuity_ReportType">
		<sequence>
			<element name="generalInfo" type="tns:generalInfoType"/>
			<element name="producer" type="string"/>
			<element name="director" type="string"/>
			<element name="directorOfPhotography" type="string"/>
			<element name="editor" type="string"/>
			<element name="continuity" type="string"/>
			<element name="continuityInfo" type="tns:continuityInfoType"/> 
		</sequence>
	</complexType>
	
	<complexType name="generalInfoType">
		<sequence>
			<element name="production" type="string"/>
			<element name="date" type="date"/>
			<element name="weekday" type="string"/>
			<element name="shootDayNo" type="integer"/>
		</sequence>
	</complexType>
	
	<complexType name="continuityInfoType">
		<sequence>
			<element name="sceneInfo" minOccurs="1"	maxOccurs="unbounded" type="tns:sceneInfoType"/>
		</sequence>
	</complexType>
				
	<complexType name="sceneInfoType">
		<sequence>
			<element name="scene" type="string" />
			<element name="slateInfo" minOccurs="1"
				maxOccurs="unbounded" type="tns:slateInfoType" />
		</sequence>
	</complexType>

	<complexType name="slateInfoType">
		<sequence>
			<element name="slate" type="integer" />
			<element name="takeInfo" minOccurs="1" maxOccurs="unbounded" type="tns:takeInfoType" />
		</sequence>
	</complexType>

	<complexType name="takeInfoType">
		<sequence>
			<element name="take" type="integer" />
			<element name="duration" type="time" />
			<element name="print" type="boolean" />
			<element name="comments" type="string" />
			<element name="camRoll" type="string" />
			<element name="soundRoll" type="integer" />
		</sequence>
	</complexType>
</schema>

=== yawlfoundation/yawl/trunk/newyawl/filmYAWL/trunk/forms/xml/continuityInfoType.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns2:Fill_Out_Continuity_Report xmlns:ns2="http://www.yawlfoundation.org/sb/continuityInfo" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.yawlfoundation.org/sb/continuityInfo ../continuityInfoType.xsd ">
  <generalInfo>
    <production>production</production>
    <date>2001-01-01</date>
    <weekday>weekday</weekday>
    <shootDayNo>0</shootDayNo>
  </generalInfo>
  <producer>producer</producer>
  <director>director</director>
  <directorOfPhotography>directorOfPhotography</directorOfPhotography>
  <editor>editor</editor>
  <continuity>continuity</continuity>
  <continuityInfo>
    <sceneInfo>
      <scene>scene</scene>
      <slateInfo>
        <slate>slate</slate>
        <takeInfo>
          <take>0</take>
          <duration>12:00:00</duration>
          <print>true</print>
          <comments>comments</comments>
          <camRoll>camRoll</camRoll>
          <soundRoll>soundRoll</soundRoll>
        </takeInfo>
      </slateInfo>
    </sceneInfo>
  </continuityInfo>
  <finalSubmission>true</finalSubmission>
</ns2:Fill_Out_Continuity_Report>
